name: shared_map
description: Offers a versatile, synchronized Map for efficient sharing between Dart application parts, including Isolates or external apps.
version: 1.1.9
repository: https://github.com/gmpassos/shared_map

environment:
  sdk: ^3.0.0

#dependencies:
  # collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8
  dependency_validator: ^3.2.3
  coverage: ^1.8.0
